name: Upload Docker image

on: 
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      version:
        required: false
        type: string
    secrets:
      GIT_HUB_PAT:
        required: true

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: utilant/ci_runner
          ref: feat/adding_versioning_logic
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github
      - name: Docker build and push
        if: ${{ !inputs.version = '' }}
        run: python3 .github/scripts/docker_push.py ${{ inputs.image }}
      - name: Docker build and push
        if: ${{ inputs.version != '' }}
        run: |
          python3 .github/scripts/update_version.py --version ${{ inputs.version }}
          python3 .github/scripts/docker_push.py ${{ inputs.image }} --release ${{ inputs.version }}